Hero
front-end-by-rimantas/18-grupe-portfolio-saas-one pull request #26
Opened 2020-10-09 22:08 UTC by rositatisor

2020-10-09 22:44 UTC, Matulanas approved these changes
Reikia Responsive

2020-10-10 09:08 UTC, ievaza requested changes
Reikia responsive design

2020-10-10 09:55 UTC, ievaza approved these changes

2020-10-10 10:00 UTC, IgnasKazenas approved these changes

2020-10-10 10:44 UTC, merged