Home page about
front-end-by-rimantas/18-grupe-portfolio-saas-one pull request #28
Opened 2020-10-09 22:42 UTC by Matulanas

2020-10-10 09:31 UTC, ievaza requested changes
Kai resposive design pasidarai, "right-block" turi labai dideli margin-top, tai reikia nuimti.

2020-10-10 12:15 UTC, belauzas requested changes
Negalima daryti PR, jei matyti, jog negalimas automatinis "merge", t.y. egzistuoja GIT conflict'ai. Užduoties autorius turi tai ištaisyti, prieš kurdamas PR (GIF FLOW pavyzdyje tai vadinama sync PR).

2020-10-10 12:16 UTC, belauzas commented
P.S. šiuo atveju problema tame, jog buvo padėtas "enter" virš komentaro, nuo kurio galima rašyti tik žemyn 👀

2020-10-10 13:17 UTC, Matulanas commented
Ištaisyta:

- GIT Conflict
- Right Block margin-top in responsive design

2020-10-10 13:45 UTC, rositatisor approved these changes, later dismissed
Ar reikia 84 eilutėj komentaro šito /* color: #a55cef; */?
Reikia nepamiršt, kad ant button eina hover'is.

2020-10-10 13:57 UTC, rositatisor requested changes
Ar reikia 84 eilutėj komentaro: /* color: #a55cef; */?
Reikia nepamiršt, kad ant button eina hover'is.

2020-10-10 14:19 UTC, belauzas submitted a review, later dismissed

2020-10-10 17:01 UTC, Matulanas commented
Updates:

- Added Button Hover
- Deleted 84 line

2020-10-10 17:04 UTC, rositatisor approved these changes

2020-10-10 19:40 UTC, PovilasZubrys approved these changes

2020-10-11 10:13 UTC, ievaza approved these changes

2020-10-11 10:17 UTC, merged