App section
front-end-by-rimantas/18-grupe-portfolio-saas-one pull request #29
Opened 2020-10-10 11:50 UTC by PovilasZubrys

2020-10-10 14:14 UTC, rositatisor requested changes
- Title reikėtų nuimti margin-left, kad tiek title, tiek p, tiek mygtukai lygiuotų kairėje pusėje;
**Pastebėjimas: 
Note: Only use one ``<h1>`` per page - this should represent the main heading/subject for the whole page.**
Reikia pakeisiti tag'ą iš h1, nes hero jau yra panaudotas h1, kuris vienintelis gali būti puslapyje. Tuomet turėtų susitvarkyti ir margin, nes dabar margin'o styling ateina nuo hero sekcijos.
- Mygtukuose neveikia Quicksand, sans-serif šriftas (nes nustatyta "Font Awesome 5 Brands") ir norėtųsi tarpelio tarp icon'ų ir teksto;

2020-10-10 16:52 UTC, rositatisor approved these changes, later dismissed

2020-10-10 17:48 UTC, Matulanas requested changes
- Right Column:

.mobile-1 klasei reiktų pakeisti **z-index** į **1**, kadangi turime tik **2** sluoksnių elementą.
                 kadangi dedame abiems sluoksniams **z-index**, tokiu atveju **position** parametras nereikalingas.
.mobile-2 reiktų uždėti **z-index -1**, kadangi turime **2** sluoksnių elementą ir šis elementas jo yra už jo. 

- Responsive:

Didžioji dalis kodo yra perrašoma su tais pačiais parametrais.
Reiktų palikti tik tas eilutes su klasėmis, kurių parametrus keiti pasikeičiant rezoliucijai. 

- Trūksta Buttons hoverio

2020-10-10 19:54 UTC, Matulanas approved these changes

2020-10-11 10:32 UTC, rositatisor approved these changes

2020-10-11 10:46 UTC, ievaza approved these changes

2020-10-11 10:46 UTC, merged