JA FAQ
front-end-by-rimantas/18-grupe-portfolio-saas-one pull request #75
Opened 2020-10-17 21:02 UTC by rositatisor

2020-10-18 07:54 UTC, belauzas requested changes

2020-10-18 07:54 UTC, belauzas commented on css/custom.css
> +                .FAQ .QA > .question-and-icon:hover {
klasių pavadinimai turėtų būti iš mažųjų raidžių

2020-10-18 12:58 UTC, rositatisor commented on css/custom.css
> +                .FAQ .QA > .question-and-icon:hover {
done

2020-10-18 14:38 UTC, PovilasZubrys approved these changes

2020-10-18 18:22 UTC, belauzas approved these changes

2020-10-19 06:46 UTC, Matulanas approved these changes

2020-10-19 06:49 UTC, merged