Js  address
front-end-by-rimantas/18-grupe-portfolio-saas-one pull request #83
Opened 2020-10-20 09:09 UTC by PovilasZubrys

JS address section

2020-10-20 09:12 UTC, IgnasKazenas submitted a review, later dismissed

2020-10-20 14:43 UTC, rositatisor commented on js/components/address/isValidAddress.js
> +        errors.push('ERROR: paslaugos aktyvumo statusas turi buti boolean');
Ne "paslaugos" aktyvumą tikriname, o adreso.

2020-10-20 14:46 UTC, rositatisor commented on js/components/address/isValidAddress.js
> +    if (typeof address.text !== 'string') {
Antrame stulpelyje address.text yra el. paštas, gal būtų vertinga pakeisti property pavadinimą? Taip pat trūksta validacijų susijusių su el.paštu, pavyzdžiui, dabar vietoj el. pašto galiu įvesti belekokius skaičius ir juos vis tiek spausdina.

2020-10-20 14:47 UTC, rositatisor commented on js/components/address/isValidAddress.js
> +export { isValidAddress }
Trūksta phone validacijų, nes pavyzdžiui, įrašius boolean, jį ir spausdina.

2020-10-20 14:49 UTC, rositatisor commented on js/components/address/isValidAddress.js
> +export { isValidAddress }
Trūksta validacijų dėl "social link'ų". Pavyzdžiui, jeigu nebūtų nei vienos social link'o iconos, gal nereikėtų rodyti, kad galima susisiekti?

2020-10-20 14:51 UTC, rositatisor requested changes
Komentarai kode.

2020-10-22 08:06 UTC, Matulanas approved these changes

2020-10-22 08:11 UTC, ievaza approved these changes

2020-10-22 08:12 UTC, rositatisor approved these changes

2020-10-22 08:12 UTC, merged